### ISSUE TITLE
primaryHeaderTitle and secondaryHeaderTitle Not working

### ISSUE THREAD

**Issue by tushar66** [BadhanGanesh/BJOTPViewController#1]
oneTimePasswordVC.primaryHeaderTitle = "Enter OTP"
 oneTimePasswordVC.secondaryHeaderTitle = "Enter OTP"

Not showing the labels.

**Comment by BadhanGanesh-HappyFox** [comment]
@tushar66 Can you please show the whole code? Have you set `hideLabelsWhenEditing` to true? This will hide the labels when the keyboard is ON.

**Comment by BadhanGanesh** [comment]
@tushar66 Can you please show the whole code? Have you set `hideLabelsWhenEditing` to true? This will hide the labels when the keyboard is ON.

**Comment by tushar66** [comment]
Its Working Now. Sorry to disturb.

Tnank You.

**Comment by BadhanGanesh** [comment]
@tushar66 Cool. No problem.

**Comment by BadhanGanesh** [comment]
@tushar66 This is actually an issue as you originally reported; I'm reopening this now. The current release (v2.3.1) has this, where you have to set both `primaryHeaderTitle` and `secondaryHeaderTitle` to make it appear. Setting only one will not even create the labels. I've noted this and will be fixed in the next release. Thanks for reporting.
